application: io-2011-html5-games
version: 1
runtime: python
api_version: 1

#default_expiration: "30d"

handlers:
    
- url: /(.*\.appcache)
  static_files: static/\1
  mime_type: text/cache-manifest
  upload: static/(.*\.appcache)

- url: (.*)/
  static_files: static\1/index.html
  upload: static/index.html

- url: /
  static_dir: static
  
